const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),all=require('../voiced-comics-data.js'),variants=require('../comic-language-variants.js'),j3=all.filter(c=>c.lesson==='j3');
const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
test('J3 appends without changing any of the 59 prior Japanese or English records',()=>{assert.equal(all.length,75);assert.equal(hash(JSON.stringify(all.slice(0,59))),'ab29e3024ebd380e89b68321cc51aaaed411ca29560d685896024773b5a6c268');assert.equal(Object.keys(variants).length,75);assert.equal(hash(JSON.stringify(Object.fromEntries(Object.entries(variants).filter(([id])=>!id.startsWith('j3-'))))),'6b51fb98bb5bef4fd8453108fb1f2abd71a983c4fcc0bcd0a1a6fb96b150ca74');});
test('J3 contains exactly 16 comics, 64 panels, 55 audible cues and 10 silent explanations',()=>{assert.equal(j3.length,16);assert.equal(j3.flatMap(c=>c.panels).length,64);const cues=j3.flatMap(c=>c.cues);assert.equal(cues.filter(q=>q.text).length,55);assert.equal(cues.filter(q=>!q.text).length,10);assert.equal(cues.filter(q=>q.sourceKind==='original').length,46);assert.equal(cues.filter(q=>q.sourceKind==='added').length,9);assert.equal(cues.filter(q=>q.sourceKind==='editorial').length,10);for(const c of j3){assert.equal(c.series,'beginner-review');assert.match(c.label,/初級複習 J3/);assert.ok(variants[c.id].en);for(const q of c.cues){assert.equal(!q.text,q.skipAudio);assert.ok(q.sourceLabel);assert.equal(c.panels[q.panel].skipAudio,q.skipAudio)}}});
test('J3 has its own filter, 16 bilingual voice links, and truthful total',()=>{const html=fs.readFileSync(path.join(root,'japanese-comics.html'),'utf8');assert.equal((html.match(/data-lesson="j3"/g)||[]).length,16);assert.match(html,/data-filter="j3"[^>]*>初級複習 J3 <span>16/);assert.match(html,/data-filter="all"[^>]*>全部 <span>75/);assert.equal((html.match(/有聲漫畫 · 日語朗讀與跟讀/g)||[]).length,0);assert.equal((html.match(/有聲漫畫 · 日文／英文切換/g)||[]).length,75);assert.doesNotMatch(html,/59 張皆可/)});
test('J3 when comic preserves both ordered utterances in its fourth panel',()=>{const c=j3.find(c=>c.id==='j3-06-when');assert.deepEqual(c.cues.map(q=>q.panel),[0,1,2,3,3]);assert.equal(c.panels[3].first,3);assert.equal(c.cues[3].text,'いそがしいとき、ごはんをたべません。');assert.equal(c.cues[4].text,'ひまなとき、かんこくドラマをみます。')});
test('J3 corrections, conjugations and silent positions are retained',()=>{assert.equal(j3[0].cues[2].text,'きます、くる、こない、こなかった。');assert.equal(j3[14].cues[2].text,'きます、こよう。');assert.match(j3[13].cues[0].text,/^おうさん/);assert.ok(j3[13].cues[3].text.endsWith('よ。'));for(const i of [4,9,11])assert.deepEqual(j3[i].cues.map(q=>!!q.text),[true,false,true,false]);assert.equal(j3[12].cues[1].text,'');assert.match(j3[15].cues[3].text,/ごごよじ/)});
test('J3 has only approved public content and no private provenance or source dates',()=>{assert.doesNotMatch(JSON.stringify(j3),/libfile_|libraryFileId|sourcePackage|sourceSegments|sourceReferences|sourceMessages|sourceAudit|oneNotePageId|sourceSlide|\/workspace\/|onenote:|sharepoint\.com|1drv\.ms|2026[-\/]10[-\/]04/i);assert.ok(!all.some(c=>/^j[4-6]-|^l6-/.test(c.id)))});
